### ISSUE TITLE
Getting errors when trying to use the provided examples

### ISSUE THREAD

**Issue by AndersenJ** [mkay581/carousel-module#4]
When trying to use your examples, they fail to load and throw the following errors: 

Error: Module name "carousel-panels" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
TypeError: Carousel is not a constructor

I set the path to carousel.js, and don't see anywhere else that I could have made a mistake. It's hosted at http://52.11.83.207/nerf/carousel-with-thumbnails.html

I understand if you don't care to maintain this anymore, but would still appreciate it if you could take a look and let me know what's going on!

Thanks!

**Comment by markcellus** [comment]
Hey, I took a look and looks like your carousel-js file is not being found at http://52.11.83.207/nerf/carousel-js/src/carousel.js. Has it been uploaded correctly?

Also, I'm definitely still maintaining. I've been working on updated version coming out soon with additional functionality. However it may be good to note that eventually the "built" version of this package ([dist](https://github.com/mkay581/carousel-js/tree/1.4.1/dist) folder) will require a manual build, but that will be pretty easy and I'll make sure its documented thoroughly.

**Comment by AndersenJ** [comment]
Sorry about that, I must have moved something around when I was trying to fix it. Try again now.

**Comment by markcellus** [comment]
Oh I see that you are using the core carousel-js file. If you are not compiling manually, you have to use one of the versions in the [dist](https://github.com/mkay581/carousel-js/tree/1.4.1/dist) folder. Replace your carousel-js file with one of those.

**Comment by AndersenJ** [comment]
Much better, thank you!

**Comment by markcellus** [comment]
No problem, thanks and let me know if I can help out with anything else.
